### ISSUE TITLE
Please, support 64-bit seed. This is needed for compatibility with ffmpeg

### ISSUE THREAD

**Issue by safinaskar** [kurtbuilds/fastmurmur3#4]
I'm attempting to generate the same murmur3 hash values as ffmpeg generates. But it seems to use particular 64-bit seed ( https://git.ffmpeg.org/gitweb/ffmpeg.git/blob/1617d1a752d5e97d5e74f6c384609c027c884553:/libavutil/murmur3.c#l48 ). So, please, support 64-bit seeds

(The same bug applies to "murmur3" crate ( https://github.com/stusmall/murmur3/issues/21 ))

**Comment by kurtbuilds** [comment]
The tests aren't running, because the tests also run benchmarks, which involve building cpp and c versions which I don't have time ATM to set up. Ideally the benchmarks should move to a different repo so that tests for the Rust code can be run independently.

Anyway, that u32 parameter is immediately cast to u64, so there it appears to be a trivial change to change that to a u64.

I just changed the parameter to a u64 and cut a release as 0.2.0.

If there's additional changes you need, I welcome a PR.

**Comment by safinaskar** [comment]
@kurtbuilds , I just tested. And I see your implementation produces the same answers the crate "murmurhash" produces. Thanks!
